import type { Metadata } from "next";
import { Geist, Manrope } from "next/font/google";
import "./globals.css";

const geist = Geist({
  weight: ["400", "700"],
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap", 
});

const manrope = Manrope({
  weight: ["400", "500"],
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geist.variable} ${manrope.variable}`}>
      <head>
        {/* Preload fonts to avoid loading delays */}
        <link
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Geist:wght@400;700&subset=latin&display=swap"
          as="style"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500&subset=latin&display=swap"
          as="style"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Geist+Mono:wght@400&subset=latin&display=swap"
          as="style"
          crossOrigin="anonymous"
        />
      </head>
      <body className="font-geist antialiased">
        {children}
      </body>
    </html>
  );
}