import type { Metadata } from "next";
import { Geist, Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";

const geist = Geist({
  weight: ["400", "700"],
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const manrope = Manrope({
  weight: ["400", "500"],
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geist.variable} ${manrope.variable}`}>
      <body className="font-geist antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
